# ApplicationSet Example 4: Cluster Generator
# Automatically deploys to all clusters registered in ArgoCD
# Add a new cluster to ArgoCD = Application automatically deployed!

apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-generator-demo
  namespace: argocd
spec:
  generators:
  # Cluster generator - deploys to all ArgoCD-registered clusters
  - clusters:
      # Optional: filter clusters by labels
      selector:
        matchLabels:
          # Only deploy to clusters with this label
          # argocd.argoproj.io/secret-type: cluster
          env: production
  template:
    metadata:
      # {{name}} = cluster name, {{server}} = cluster API server URL
      name: 'app-blue-{{name}}'
      labels:
        app.kubernetes.io/name: app-blue
        cluster: '{{name}}'
        generator: cluster
    spec:
      project: default
      source:
        repoURL: https://github.com/YOUR_USERNAME/argocd-applicationset-demo.git
        targetRevision: HEAD
        path: apps/app-blue
      destination:
        # {{server}} is the cluster's API server URL
        server: '{{server}}'
        namespace: demo-blue
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
