apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: grafan-deploy
  name: grafan-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafan-deploy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: grafan-deploy
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
