# Wave 0: PreSync Hook
apiVersion: batch/v1
kind: Job
metadata:
  name: vm-metrics-app-presync
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-wave: "0"
spec:
  template:
    spec:
      containers:
      - name: presync
        image: busybox
        command: 
        - sh
        - -c
        - |
          echo "============================================"
          echo "       PRESYNC HOOK - WAVE 0               "
          echo "============================================"
          echo ""
          echo "Time: $(date)"
          echo ""
          echo "Step 1: Checking database connection..."
          sleep 10
          echo "Step 2: Running database migrations..."
          sleep 10
          echo "Step 3: Validating configuration..."
          sleep 10
          echo ""
          echo "PreSync completed successfully!"
          echo "============================================"
      restartPolicy: Never
  backoffLimit: 1
---
# Wave 1: Service
apiVersion: v1
kind: Service
metadata:
  name: vm-metrics-app-service
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  type: NodePort
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
    nodePort: 30002
  selector:
    app: vm-metrics-app
---
# Wave 2: Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vm-metrics-app
  labels:
    app: vm-metrics-app
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vm-metrics-app
  template:
    metadata:
      labels:
        app: vm-metrics-app
    spec:
      containers:
      - name: vm-metrics-app
        image: rahees9983/vm-metrics-app:with-gui
        ports:
        - containerPort: 5000
---
# Wave 3: PostSync Hook
apiVersion: batch/v1
kind: Job
metadata:
  name: vm-metrics-app-postsync
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-wave: "3"
spec:
  template:
    spec:
      containers:
      - name: postsync
        image: busybox
        command:
        - sh
        - -c
        - |
          echo "============================================"
          echo "       POSTSYNC HOOK - WAVE 3              "
          echo "============================================"
          echo ""
          echo "Time: $(date)"
          echo ""
          echo "Step 1: Running health check..."
          sleep 10
          echo "Step 2: Running smoke tests..."
          sleep 10
          echo "Step 3: Sending deployment notification..."
          sleep 10
          echo ""
          echo "PostSync completed successfully!"
          echo "============================================"
      restartPolicy: Never
  backoffLimit: 1
---
# SyncFail Hook
apiVersion: batch/v1
kind: Job
metadata:
  name: vm-metrics-app-syncfail
  annotations:
    argocd.argoproj.io/hook: SyncFail
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  template:
    spec:
      containers:
      - name: syncfail
        image: busybox
        command:
        - sh
        - -c
        - |
          echo "============================================"
          echo "       SYNCFAIL HOOK - ERROR!              "
          echo "============================================"
          echo ""
          echo "Time: $(date)"
          echo ""
          echo "Step 1: Capturing error logs..."
          sleep 10
          echo "Step 2: Sending Slack notification..."
          sleep 10
          echo "Step 3: Creating incident ticket..."
          sleep 10
          echo ""
          echo "SyncFail hook completed!"
          echo "============================================"
      restartPolicy: Never
  backoffLimit: 1
